### ISSUE TITLE
 Making use of vanilla-framework without NPM for Jekyll Scss.

### ISSUE THREAD

**Issue by csharpee** [canonical/vanilla-framework#4757]
Hi :wave:  I joined the #[vanilla-framework](https://github.com/canonical/vanilla-framework) chat, but I was the only one in the room, so I am asking the question here. 

I am using vanilla-framework latest version. 

I am having trouble integrating [vanilla-framework](https://github.com/canonical/vanilla-framework) into my Jekyll project that doesn't use NPM. 

Is there an example of integrating this into Jekyll? I would like to keep the scss and how it is organized, but I receive use math errors when building with jekyll. I included other scss projects quite easily, but am having trouble with this framework. 

I copied the scss files over into vanilla-framework folder and imported the _vanilla.scss, but that didn't work.

I haven't found any examples integrating this framework **without** nodejs or npm.

the error I receive is: 

```
hydenjekyllorg-jekyll-serve-1  |   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
hydenjekyllorg-jekyll-serve-1  |                     Error: Invalid CSS after "... $value: math": expected expression (e.g. 1px, bold), was ".div($value, $numbe" on line 96:19 of _scss/libs/vanilla-framework/_global_functions.scss from line 7:1 of _scss/libs/vanilla-framework/_settings.scss from line 1:1 of _scss/libs/vanilla-framework/_vanilla.scss from line 3:1 of _scss/styles.scss from line 1:1 of main.scss >> $value: math.div($value, $number); ------------------^ 
hydenjekyllorg-jekyll-serve-1  | /usr/gem/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:200:in `rescue in sass_convert': Error: Invalid CSS after "...   $value: math": expected expression (e.g. 1px, bold), was ".div($value, $numbe" (Jekyll::Converters::Scss::SyntaxError)
hydenjekyllorg-jekyll-serve-1  |         on line 96:19 of _scss/libs/vanilla-framework/_global_functions.scss
hydenjekyllorg-jekyll-serve-1  |         from line 7:1 of _scss/libs/vanilla-framework/_settings.scss
hydenjekyllorg-jekyll-serve-1  |         from line 1:1 of _scss/libs/vanilla-framework/_vanilla.scss
hydenjekyllorg-jekyll-serve-1  |         from line 3:1 of _scss/styles.scss
hydenjekyllorg-jekyll-serve-1  |         from line 1:1 of main.scss
hydenjekyllorg-jekyll-serve-1  | >>       $value: math.div($value, $number);
hydenjekyllorg-jekyll-serve-1  | 
hydenjekyllorg-jekyll-serve-1  |    ------------------^
```

in _global_functions.scss line 96

```
// Raises a number to a power (https://css-tricks.com/snippets/sass/power-function/)
@function pow($number, $exponent) {
  $value: 1;

  @if $exponent > 0 {
    @for $i from 1 through $exponent {
      $value: $value * $number;
    }
  } @else if $exponent < 0 {
    @for $i from 1 through -$exponent {
      $value: math.div($value, $number);
    }
  }

  @return $value;
}
```

**Comment by csharpee** [comment]
The **math.div** function seems to be the problem.

**Comment by csharpee** [comment]
I am now having trouble with this function. 

```
@mixin vf-chip-theme($chip-type: neutral, $is-interactive: false, $colors-chip-tinted-backgrounds, $colors-chip-tinted-borders, $color-chip-value, $color-chip-lead) {
  @if (not map-has-key($colors-chip-tinted-backgrounds, $chip-type)) {
    $chip-type: neutral;
  }
```

the error is: 
```
hydenjekyllorg-jekyll-serve-1  |   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
hydenjekyllorg-jekyll-serve-1  |                     Error: required parameters must precede optional parameters on line 234 of _scss/libs/vanilla-framework/_patterns_chip.scss >> ip-type: neutral, $is-interactive: false, $colors-chip-tinted-backgrounds, $ ------------------------------------------^ 
hydenjekyllorg-jekyll-serve-1  | /usr/gem/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:200:in `rescue in sass_convert': Error: required parameters must precede optional parameters (Jekyll::Converters::Scss::SyntaxError)
hydenjekyllorg-jekyll-serve-1  |         on line 234 of _scss/libs/vanilla-framework/_patterns_chip.scss
hydenjekyllorg-jekyll-serve-1  | >> ip-type: neutral, $is-interactive: false, $colors-chip-tinted-backgrounds, $
hydenjekyllorg-jekyll-serve-1  |    ------------------------------------------^

```

**Comment by csharpee** [comment]
I have another error:  **Error: Function hsl is missing argument $saturation.**

```
hydenjekyllorg-jekyll-serve-1  |   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
hydenjekyllorg-jekyll-serve-1  |                     Error: Function hsl is missing argument $saturation. on line 14:9 of _scss/libs/vanilla-framework/_settings.scss from line 1:9 of _scss/libs/vanilla-framework/_vanilla.scss from line 3:9 of _scss/styles.scss from line 1:9 of main.scss >> default: hsl(129deg 90% 39% / 10%), -------------^ 
hydenjekyllorg-jekyll-serve-1  | /usr/gem/gems/jekyll-sass-converter-2.2.0/lib/jekyll/converters/scss.rb:200:in `rescue in sass_convert': Error: Function hsl is missing argument $saturation. (Jekyll::Converters::Scss::SyntaxError)
hydenjekyllorg-jekyll-serve-1  |         on line 14:9 of _scss/libs/vanilla-framework/_settings.scss
hydenjekyllorg-jekyll-serve-1  |         from line 1:9 of _scss/libs/vanilla-framework/_vanilla.scss
hydenjekyllorg-jekyll-serve-1  |         from line 3:9 of _scss/styles.scss
hydenjekyllorg-jekyll-serve-1  |         from line 1:9 of main.scss
hydenjekyllorg-jekyll-serve-1  | >>     default: hsl(129deg 90% 39% / 10%),
hydenjekyllorg-jekyll-serve-1  | 
hydenjekyllorg-jekyll-serve-1  |    -------------^

```

**Comment by csharpee** [comment]
Now, in my main.css converted file, I get the following. . . 

```
@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';@use 'sass:math';/*!
```

**Comment by bartaz** [comment]
Hi @csharpee, do you know what's the version of sass used by Jekyll?

Vanilla (starting with version 3.0) requires Dart version of Sass: https://www.npmjs.com/package/sass to be built. It seems that Sass built into Jekyll is an older version that doesn't support all the features we currently use in Vanilla. Sorry.

**Comment by csharpee** [comment]
> 

I am unsure what Dart Sass version Jekyll is using, I assume it is 1.6.2.

Also, Jekyll doesn't manage Dart Sass version and relies on a embedded host to compile Dart Sass.

**Comment by bartaz** [comment]
@csharpee I don't think it's an error with Dart Sass, Vanilla fully supports latest version of Dart Sass.

I would need to know more about your specific environment and how the sass is being built in it. It seems that issue may be somewhere between Sass, jekyll-sass-converter, sass-embedded or whatever else there is in the pipeline.

Recommended way of building Vanilla is using sass, directly installed via npm.

You can always use a pre-built version hotlinked: https://assets.ubuntu.com/v1/vanilla-framework-version-3.14.0.min.css

**Comment by csharpee** [comment]
Yeah, I moved on to another css framework, but would of loved to have Ubuntu's. . I personally don't use nodejs or npm for anything; all this javascript has become a bit outrageous in my opinion. .

I tested the min.css already and had exactly the same errors as I had with the vanilla scss.

**Comment by bartaz** [comment]
With pre-built CSS version you can simply hotlink it in your template:

```
<link rel="stylesheet" href="https://assets.ubuntu.com/v1/vanilla-framework-version-3.14.0.min.css" />
```
See https://vanillaframework.io/docs#hotlink

Or download the file to your project and link it as CSS in HTML, you don't need to build it again.

**Comment by csharpee** [comment]
I want to keep my site files local, static and quickly available without 3rd party providers; plus, I don't need all the components that comes with that ~400Kb.min.css file.

Building it allows me to prune and only use the necessary components that are being used on my site.
